<script>
  // For demo purposes only, hard-wiring img paths from Vite
  // @ts-ignore img
  import imageXl from '../imgs/demo-xl.jpg';
  // @ts-ignore img
  import imageLg from '../imgs/demo-lg.jpg';
  // @ts-ignore img
  import imagePngOverlayXl from '../imgs/layer-overlay-xl.png';

  let {
    assetsPath = '/',
    onAiMounted = () => {},
    onArtboardChange = () => {},
    taggedText = { text: {}, htext: {} },
    debugTaggedText = false,
    artboardWidth = $bindable(undefined),
  } = $props();
  import { onMount, untrack } from 'svelte';
  let aiBox;
  let screenWidth = $state(0);
  let aiBoxWidth = $derived(artboardWidth ?? screenWidth);
  let activeArtboard = $state(undefined);
  onMount(() => {
    onAiMounted();
  });
  $effect(() => {
    if (aiBoxWidth) {
      const currentArtboard = aiBox.querySelectorAll('.g-artboard')[0];
      if (currentArtboard?.id !== activeArtboard?.id) {
        activeArtboard = untrack(() => currentArtboard);
        onArtboardChange(activeArtboard);
      }
    }
  });
</script>

<svelte:window bind:innerWidth={screenWidth} />

<div
  id="g-demo-box"
  class="ai2svelte"
  bind:this={aiBox}
  style:--debug-tagged-text={debugTaggedText ? 'visible' : 'hidden'}
>
  <!-- Artboard: lg -->
  {#if aiBoxWidth && aiBoxWidth >= 0 && aiBoxWidth < 800}
    <div
      id="g-demo-lg"
      class="g-artboard"
      style="max-width: 799px;aspect-ratio: 2.75483870967742;"
      data-aspect-ratio="2.755"
      data-min-width="0"
      data-max-width="799"
    >
      <div
        id="g-demo-lg-img"
        class="g-demo-lg-img g-aiImg"
        alt=""
        style="background-image: url({imageLg});"
        loading="lazy"
      ></div>
    </div>
  {/if}
  <!-- Artboard: xl -->
  {#if aiBoxWidth && aiBoxWidth >= 800}
    <div
      id="g-demo-xl"
      class="g-artboard"
      style="min-width: 800px;aspect-ratio: 6.6758064516129;"
      data-aspect-ratio="6.676"
      data-min-width="800"
    >
      <div
        id="g-demo-xl-img"
        class="g-demo-xl-img g-aiImg"
        alt=""
        style="background-image: url({imageXl});"
        loading="lazy"
      ></div>
      <div
        id="g-png-layer-overlay-xl"
        class="g-png-layer-overlay g-aiImg"
        alt=""
        style="opacity:1;;background-image: url({imagePngOverlayXl});"
        loading="lazy"
      ></div>
      <div
        id="g-caption2"
        class="g-captions g-aiAbs"
        style="top:38.5484%;left:23.6715%;width:5.2428%;"
      >
        <p
          class="g-pstyle0 g-taggedText g-htext"
          data-tagged-type="HTEXT"
          data-tagged-prop="captions.caption2"
        >
          {@html taggedText?.htext?.captions?.caption2 || ''}
        </p>
      </div>
      <div
        id="g-caption3"
        class="g-captions g-aiAbs"
        style="top:38.5484%;left:49.4749%;width:5.2428%;"
      >
        <p
          class="g-pstyle0 g-taggedText g-htext"
          data-tagged-type="HTEXT"
          data-tagged-prop="captions.caption3"
        >
          {@html taggedText?.htext?.captions?.caption3 || ''}
        </p>
      </div>
      <div
        id="g-caption4"
        class="g-captions g-aiAbs"
        style="top:38.5484%;left:83.976%;width:5.2428%;"
      >
        <p
          class="g-pstyle0 g-taggedText g-htext"
          data-tagged-type="HTEXT"
          data-tagged-prop="captions.caption4"
        >
          {@html taggedText?.htext?.captions?.caption4 || ''}
        </p>
      </div>
      <div
        id="g-caption1"
        class="g-captions g-aiAbs"
        style="top:38.5484%;left:2.966%;width:3.4791%;"
      >
        <p
          class="g-pstyle0 g-taggedText g-htext"
          data-tagged-type="HTEXT"
          data-tagged-prop="captions.caption1"
        >
          {@html taggedText?.htext?.captions?.caption1 || ''}
        </p>
      </div>
    </div>
  {/if}
</div>

<!--

TAGGED TEXT PROPS

taggedText={{
{
  "text": {
    
  },
  "htext": {
    "captions": {
      "caption1": "",
      "caption2": "",
      "caption3": "",
      "caption4": ""
    }
  }
}
}}

-->
<!-- End ai2svelte - 2026-01-07 11:23 -->

<!-- Generated by ai2svelte v1.0.3 - 2026-01-07 11:23 -->
<!-- ai file: demo.ai -->
<style lang="scss">
  #g-demo-box,
  #g-demo-box .g-artboard {
    margin: 0 auto;
  }
  #g-demo-box .g-artboard {
    margin: 0 auto;
    min-height: 100%;
    min-width: unset !important;
    max-width: unset !important;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
  }
  #g-demo-box p {
    margin: 0;
  }
  #g-demo-box .g-aiAbs {
    position: absolute;
  }
  #g-demo-box .g-aiImg {
    position: absolute;
    top: 0;
    display: block;
    width: 100% !important;
    height: 100%;
    background-size: contain;
    background-repeat: no-repeat;
  }
  #g-demo-box .g-aiSymbol {
    position: absolute;
    box-sizing: border-box;
  }
  #g-demo-box .g-aiPointText p {
    white-space: nowrap;
  }
  #g-demo-box {
    height: 100%;
  }
  #g-demo-lg {
    position: relative;
    overflow: hidden;
  }
  #g-demo-xl {
    position: relative;
    overflow: hidden;
  }
  #g-demo-xl p {
    font-family: var(--theme-font-family-sans-serif), Knowledge, sans-serif;
    font-weight: regular;
    line-height: 22px;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 18px;
    text-align: left;
    color: rgb(0, 0, 0);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    height: auto;
    position: static;
  }
  #g-demo-xl .g-pstyle0 {
    font-weight: 400;
  }

  /* Custom CSS */

  .g-taggedText:empty::before {
    content: attr(data-tagged-type);
    padding: 0px 4px;
    font-size: 0.6rem;
    color: #fff;
    background-color: black;
    display: block;
    font-weight: 800;
    visibility: var(--debug-tagged-text, hidden);
  }

  .g-taggedText:empty::after {
    content: attr(data-tagged-prop);
    padding: 0px 4px;
    font-size: 0.8rem;
    color: #fff;
    font-weight: 500;
    visibility: var(--debug-tagged-text, hidden);
  }

  .g-taggedText:empty {
    background-color: #00000088;
    outline: 2px solid black;
    visibility: var(--debug-tagged-text, hidden);
  }
</style>
