<script>
  import { assets } from '$app/paths';
  let width = null;
</script>

<!-- Generated by ai2html v0.100.0 - 2022-02-14 14:47 -->

<div id="g-ai-linechart-box" bind:clientWidth="{width}">
  <!-- Artboard: xs -->
  {#if width && width >= 0 && width < 510}
    <div id="g-ai-linechart-xs" class="g-artboard" style="">
      <div style="padding: 0 0 187.8788% 0;"></div>
      <div
        id="g-ai-linechart-xs-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/ai-linechart-xs.png);"
      ></div>
    </div>
  {/if}
  <!-- Artboard: sm -->
  {#if width && width >= 510 && width < 660}
    <div id="g-ai-linechart-sm" class="g-artboard" style="">
      <div style="padding: 0 0 121.5686% 0;"></div>
      <div
        id="g-ai-linechart-sm-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/ai-linechart-sm.png);"
      ></div>
    </div>
  {/if}
  <!-- Artboard: md -->
  {#if width && width >= 660 && width < 930}
    <div id="g-ai-linechart-md" class="g-artboard" style="">
      <div style="padding: 0 0 52.7353% 0;"></div>
      <div
        id="g-ai-linechart-md-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/ai-linechart-md.png);"
      ></div>
      <div
        id="g-ai2-1"
        class="g-ai2html-settings g-aiAbs g-aiPointText"
        style="top:10.8355%;margin-top:-9.7px;left:10.3982%;width:41px;"
      >
        <p class="g-pstyle0">5%</p>
      </div>
      <div
        id="g-ai2-2"
        class="g-ai2html-settings g-aiAbs g-aiPointText"
        style="top:29.5108%;margin-top:-9.7px;left:10.3982%;width:29px;"
      >
        <p class="g-pstyle0">0</p>
      </div>
      <div
        id="g-ai2-3"
        class="g-ai2html-settings g-aiAbs g-aiPointText"
        style="top:35.0946%;margin-top:-11.1px;left:84.3799%;width:55px;"
      >
        <p class="g-pstyle1">Dow</p>
      </div>
      <div
        id="g-ai2-4"
        class="g-ai2html-settings g-aiAbs g-aiPointText"
        style="top:39.9791%;margin-top:-11.1px;left:84.3801%;width:83px;"
      >
        <p class="g-pstyle2">S&amp;P 500</p>
      </div>
      <div
        id="g-ai2-5"
        class="g-ai2html-settings g-aiAbs g-aiPointText"
        style="top:48.3111%;margin-top:-11.1px;left:84.3801%;width:78px;"
      >
        <p class="g-pstyle3">Nasdaq</p>
      </div>
      <div
        id="g-ai2-6"
        class="g-ai2html-settings g-aiAbs g-aiPointText"
        style="top:48.1861%;margin-top:-9.7px;left:10.3982%;width:36px;"
      >
        <p class="g-pstyle0">&minus;5</p>
      </div>
      <div
        id="g-ai2-7"
        class="g-ai2html-settings g-aiAbs g-aiPointText"
        style="top:67.1488%;margin-top:-9.7px;left:10.3982%;width:43px;"
      >
        <p class="g-pstyle0">&minus;10</p>
      </div>
      <div
        id="g-ai2-8"
        class="g-ai2html-settings g-aiAbs g-aiPointText"
        style="top:85.8241%;margin-top:-9.7px;left:10.3982%;width:43px;"
      >
        <p class="g-pstyle0">&minus;15</p>
      </div>
      <div
        id="g-ai2-9"
        class="g-ai2html-settings g-aiAbs g-aiPointText"
        style="top:93.0069%;margin-top:-9.7px;left:28.7755%;width:92px;"
      >
        <p class="g-pstyle0">Jan. 2, 2022</p>
      </div>
      <div
        id="g-ai2-10"
        class="g-ai2html-settings g-aiAbs g-aiPointText"
        style="top:93.0069%;margin-top:-9.7px;left:73.7228%;width:57px;"
      >
        <p class="g-pstyle0">Jan. 9</p>
      </div>
    </div>
  {/if}
  <!-- Artboard: lg -->
  {#if width && width >= 930 && width < 1200}
    <div id="g-ai-linechart-lg" class="g-artboard" style="">
      <div style="padding: 0 0 66.6667% 0;"></div>
      <div
        id="g-ai-linechart-lg-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/ai-linechart-lg.png);"
      ></div>
    </div>
  {/if}
  <!-- Artboard: xl -->
  {#if width && width >= 1200}
    <div id="g-ai-linechart-xl" class="g-artboard" style="">
      <div style="padding: 0 0 51.6667% 0;"></div>
      <div
        id="g-ai-linechart-xl-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assets}/images/graphics/ai-linechart-xl.png);"
      ></div>
    </div>
  {/if}
</div>
<!-- End ai2html - 2022-02-14 14:47 -->

<!-- ai file: ai-linechart.ai -->
<style lang="scss">
  #g-ai-linechart-box,
  #g-ai-linechart-box .g-artboard {
    margin: 0 auto;
  }
  #g-ai-linechart-box p {
    margin: 0;
  }
  #g-ai-linechart-box .g-aiAbs {
    position: absolute;
  }
  #g-ai-linechart-box .g-aiImg {
    position: absolute;
    top: 0;
    display: block;
    width: 100% !important;
    height: 100%;
    background-size: contain;
    background-repeat: no-repeat;
  }
  #g-ai-linechart-box .g-aiPointText p {
    white-space: nowrap;
  }
  #g-ai-linechart-xs {
    position: relative;
    overflow: hidden;
  }
  #g-ai-linechart-sm {
    position: relative;
    overflow: hidden;
  }
  #g-ai-linechart-md {
    position: relative;
    overflow: hidden;
  }
  #g-ai-linechart-md p {
    font-family: 'Source Sans Pro', -apple-system, BlinkMacSystemFont,
      'Segoe UI', Roboto, 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-weight: 300;
    line-height: 18px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 15px;
    text-align: left;
    color: rgb(0, 0, 0);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-ai-linechart-md .g-pstyle0 {
    height: 18px;
  }
  #g-ai-linechart-md .g-pstyle1 {
    font-weight: 700;
    line-height: 20px;
    height: 20px;
    font-size: 17px;
    color: rgb(116, 196, 118);
  }
  #g-ai-linechart-md .g-pstyle2 {
    font-weight: 700;
    line-height: 20px;
    height: 20px;
    font-size: 17px;
    color: rgb(49, 130, 189);
  }
  #g-ai-linechart-md .g-pstyle3 {
    font-weight: 700;
    line-height: 20px;
    height: 20px;
    font-size: 17px;
    color: rgb(244, 193, 0);
  }
  #g-ai-linechart-lg {
    position: relative;
    overflow: hidden;
  }
  #g-ai-linechart-xl {
    position: relative;
    overflow: hidden;
  }

  /* Custom CSS */
</style>
