<!-- Generated by ai2html v0.100.0 - 2024-07-18 12:27 -->
<!-- ai file: annotation3.ai -->
<script>
  let width = null;
  // For demo purposes only, hard-wiring img paths from Vite
  // @ts-ignore
  import chart916 from '../imgs/anno_3_9_16.png';
  // @ts-ignore
  import chart11 from '../imgs/anno_3_1_1.png';
  // @ts-ignore
  import chart169 from '../imgs/anno_3_16_9.png';
  import { onMount } from 'svelte';
  export let onAiMounted = () => {};
  onMount(() => {
    onAiMounted();
  });
</script>

<div id="g-annotation3-box" bind:clientWidth="{width}">
  <!-- Artboard: Artboard_67 -->
  {#if width && width >= 1400}
    <div id="g-annotation3-Artboard_67" class="g-artboard" style="">
      <div style="padding: 0 0 56.25% 0;"></div>
      <div
        id="g-annotation3-Artboard_67-img"
        class="g-aiImg"
        alt=""
        style="{`background-image: url(${chart169});`}"
      ></div>
      <div
        id="g-ai0-1"
        class="g-text g-aiAbs g-aiPointText"
        style="top:43.5256%;margin-top:-19.8px;left:19.0027%;width:224px;"
      >
        <p class="g-pstyle0">The wave path is a short one,</p>
        <p class="g-pstyle0">only about 75-100 yards long</p>
      </div>
      <div
        id="g-ai0-2"
        class="g-text g-aiAbs g-aiPointText"
        style="top:51.805%;margin-top:-39px;left:66.9873%;width:258px;"
      >
        <p class="g-pstyle0">Fierro exits the barrel with a score</p>
        <p class="g-pstyle0">of 9.33 out of 10, as she was deep</p>
        <p class="g-pstyle0">in the tube, had good speed and</p>
        <p class="g-pstyle0">went over the foam ball on her exit</p>
      </div>
      <div
        id="g-ai0-3"
        class="g-text g-aiAbs g-aiPointText"
        style="top:76.77%;margin-top:-48.6px;left:44.8195%;width:275px;"
      >
        <p class="g-pstyle0">The wave heaves so quickly that as it</p>
        <p class="g-pstyle0">forms, it pulls water off the reef,</p>
        <p class="g-pstyle0">creating a ride that is often below</p>
        <p class="g-pstyle0">sea level - seen as the surfer exits up</p>
        <p class="g-pstyle0">and over the wave to higher water</p>
      </div>
    </div>
  {/if}
  <!-- Artboard: Artboard_68 -->
  {#if width && width >= 800 && width < 1400}
    <div id="g-annotation3-Artboard_68" class="g-artboard" style="">
      <div style="padding: 0 0 100% 0;"></div>
      <div
        id="g-annotation3-Artboard_68-img"
        class="g-aiImg"
        alt=""
        style="{`background-image: url(${chart11});`}"
      ></div>
      <div
        id="g-ai1-1"
        class="g-text g-aiAbs g-aiPointText"
        style="top:47.2955%;margin-top:-29.4px;left:14.4512%;width:170px;"
      >
        <p class="g-pstyle0">The wave path is a</p>
        <p class="g-pstyle0">short one, only about</p>
        <p class="g-pstyle0">75-100 yards long</p>
      </div>
      <div
        id="g-ai1-2"
        class="g-text g-aiAbs g-aiPointText"
        style="top:67.1205%;margin-top:-39px;left:56.4739%;width:258px;"
      >
        <p class="g-pstyle0">Fierro exits the barrel with a score</p>
        <p class="g-pstyle0">of 9.33 out of 10, as she was deep</p>
        <p class="g-pstyle0">in the tube, had good speed and</p>
        <p class="g-pstyle0">went over the foam ball on her exit</p>
      </div>
      <div
        id="g-ai1-3"
        class="g-text g-aiAbs g-aiPointText"
        style="top:89.9455%;margin-top:-48.6px;left:39.2012%;width:275px;"
      >
        <p class="g-pstyle0">The wave heaves so quickly that as it</p>
        <p class="g-pstyle0">forms, it pulls water off the reef,</p>
        <p class="g-pstyle0">creating a ride that is often below</p>
        <p class="g-pstyle0">sea level - seen as the surfer exits up</p>
        <p class="g-pstyle0">and over the wave to higher water</p>
      </div>
    </div>
  {/if}
  <!-- Artboard: Artboard_69 -->
  {#if width && width >= 0 && width < 800}
    <div id="g-annotation3-Artboard_69" class="g-artboard" style="">
      <div style="padding: 0 0 177.7778% 0;"></div>
      <div
        id="g-annotation3-Artboard_69-img"
        class="g-aiImg"
        alt=""
        style="{`background-image: url(${chart916});`}"
      ></div>
      <div
        id="g-ai2-1"
        class="g-text g-aiAbs g-aiPointText"
        style="top:46.2273%;margin-top:-39px;left:9.0404%;width:142px;"
      >
        <p class="g-pstyle0">The wave path is</p>
        <p class="g-pstyle0">a short one, only</p>
        <p class="g-pstyle0">about 75-100</p>
        <p class="g-pstyle0">yards long</p>
      </div>
      <div
        id="g-ai2-2"
        class="g-text g-aiAbs g-aiPointText"
        style="top:77.5164%;margin-top:-39px;left:49.6652%;width:258px;"
      >
        <p class="g-pstyle0">Fierro exits the barrel with a score</p>
        <p class="g-pstyle0">of 9.33 out of 10, as she was deep</p>
        <p class="g-pstyle0">in the tube, had good speed and</p>
        <p class="g-pstyle0">went over the foam ball on her exit</p>
      </div>
      <div
        id="g-ai2-3"
        class="g-text g-aiAbs g-aiPointText"
        style="top:91.7195%;margin-top:-48.6px;left:28.4723%;width:275px;"
      >
        <p class="g-pstyle0">The wave heaves so quickly that as it</p>
        <p class="g-pstyle0">forms, it pulls water off the reef,</p>
        <p class="g-pstyle0">creating a ride that is often below</p>
        <p class="g-pstyle0">sea level - seen as the surfer exits up</p>
        <p class="g-pstyle0">and over the wave to higher water</p>
      </div>
    </div>
  {/if}
</div>

<!-- End ai2html - 2024-07-18 12:27 -->

<style lang="scss">
  #g-annotation3-box,
  #g-annotation3-box .g-artboard {
    margin: 0 auto;
  }
  #g-annotation3-box p {
    margin: 0;
  }
  #g-annotation3-box .g-aiAbs {
    position: absolute;
  }
  #g-annotation3-box .g-aiImg {
    position: absolute;
    top: 0;
    display: block;
    width: 100% !important;
    height: 100%;
    background-size: contain;
    background-repeat: no-repeat;
  }
  #g-annotation3-box .g-aiPointText p {
    white-space: nowrap;
  }
  #g-annotation3-Artboard_67 {
    position: relative;
    overflow: hidden;
  }
  #g-annotation3-Artboard_67 p {
    font-family: 'Knowledge', 'Source Sans Pro', Arial, sans-serif;
    font-weight: 500;
    line-height: 19px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 16px;
    text-align: left;
    color: rgb(255, 255, 255);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-annotation3-Artboard_67 .g-pstyle0 {
    height: 19px;
  }
  #g-annotation3-Artboard_68 {
    position: relative;
    overflow: hidden;
  }
  #g-annotation3-Artboard_68 p {
    font-family: 'Knowledge', 'Source Sans Pro', Arial, sans-serif;
    font-weight: 500;
    line-height: 19px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 16px;
    text-align: left;
    color: rgb(255, 255, 255);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-annotation3-Artboard_68 .g-pstyle0 {
    height: 19px;
  }
  #g-annotation3-Artboard_69 {
    position: relative;
    overflow: hidden;
  }
  #g-annotation3-Artboard_69 p {
    font-family: 'Knowledge', 'Source Sans Pro', Arial, sans-serif;
    font-weight: 500;
    line-height: 19px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 16px;
    text-align: left;
    color: rgb(255, 255, 255);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-annotation3-Artboard_69 .g-pstyle0 {
    height: 19px;
  }

  /* Custom CSS */
  .text {
  }
</style>
