<!-- Generated by ai2html v0.100.0 - 2024-07-18 12:39 -->
<!-- ai file: annotation1.ai -->
<script>
  let width = null;
  // For demo purposes only, hard-wiring img paths from Vite
  // @ts-ignore
  import chart916 from '../imgs/anno_1_9_16.png';
  // @ts-ignore
  import chart11 from '../imgs/anno_1_1_1.png';
  // @ts-ignore
  import chart169 from '../imgs/anno_1_16_9.png';
  import { onMount } from 'svelte';
  export let onAiMounted = () => {};
  onMount(() => {
    onAiMounted();
  });
</script>

<div id="g-annotation1-box" bind:clientWidth="{width}">
  <!-- Artboard: Artboard_67 -->
  {#if width && width >= 1400}
    <div id="g-annotation1-Artboard_67" class="g-artboard" style="">
      <div style="padding: 0 0 56.25% 0;"></div>
      <div
        id="g-annotation1-Artboard_67-img"
        class="g-aiImg"
        alt=""
        style="{`background-image: url(${chart169});`}"
      ></div>
      <div
        id="g-ai0-1"
        class="g-text g-aiAbs g-aiPointText"
        style="top:19.9066%;margin-top:-19.8px;left:20.6833%;width:253px;"
      >
        <p class="g-pstyle0">Wave forms from hitting reef, and</p>
        <p class="g-pstyle0">tube will track the line of the shelf</p>
      </div>
      <div
        id="g-ai0-2"
        class="g-text g-aiAbs g-aiPointText"
        style="top:27.4494%;margin-top:-10.2px;left:75.8662%;margin-left:-85px;width:170px;"
      >
        <p class="g-pstyle1">Solid southwest swell</p>
      </div>
      <div
        id="g-ai0-3"
        class="g-text g-aiAbs g-aiPointText"
        style="top:53.0748%;margin-top:-39px;left:47.4768%;width:327px;"
      >
        <p class="g-pstyle0">Tahitian local Vahine Fierro drops into</p>
        <p class="g-pstyle0">a double overhead wave during a recent</p>
        <p class="g-pstyle0">competition. Timing and position are critical</p>
        <p class="g-pstyle0">to make the take-off and maximize scoring.</p>
      </div>
      <div
        id="g-ai0-4"
        class="g-text g-aiAbs g-aiPointText"
        style="top:87.9701%;margin-top:-19.8px;left:20.5849%;width:160px;"
      >
        <p class="g-pstyle0">Shallow water hides</p>
        <p class="g-pstyle0">a sharp reef</p>
      </div>
    </div>
  {/if}
  <!-- Artboard: Artboard_68 -->
  {#if width && width >= 800 && width < 1400}
    <div id="g-annotation1-Artboard_68" class="g-artboard" style="">
      <div style="padding: 0 0 100% 0;"></div>
      <div
        id="g-annotation1-Artboard_68-img"
        class="g-aiImg"
        alt=""
        style="{`background-image: url(${chart11});`}"
      ></div>
      <div
        id="g-ai1-1"
        class="g-text g-aiAbs g-aiPointText"
        style="top:23.9705%;margin-top:-19.8px;left:22.535%;width:253px;"
      >
        <p class="g-pstyle0">Wave forms from hitting reef, and</p>
        <p class="g-pstyle0">tube will track the line of the shelf</p>
      </div>
      <div
        id="g-ai1-2"
        class="g-text g-aiAbs g-aiPointText"
        style="top:28.3955%;margin-top:-10.2px;left:66.4%;margin-left:-85px;width:170px;"
      >
        <p class="g-pstyle1">Solid southwest swell</p>
      </div>
      <div
        id="g-ai1-3"
        class="g-text g-aiAbs"
        style="top:49.875%;left:30.953%;width:25%;"
      >
        <p>
          Tahitian local Vahine Fierro drops into a double overhead wave during
          a recent competition. Timing and position are critical to make the
          take-off and maximize scoring.
        </p>
      </div>
      <div
        id="g-ai1-4"
        class="g-text g-aiAbs g-aiPointText"
        style="top:93.7205%;margin-top:-19.8px;left:28.5123%;width:160px;"
      >
        <p class="g-pstyle0">Shallow water hides</p>
        <p class="g-pstyle0">a sharp reef</p>
      </div>
    </div>
  {/if}
  <!-- Artboard: Artboard_69 -->
  {#if width && width >= 0 && width < 800}
    <div id="g-annotation1-Artboard_69" class="g-artboard" style="">
      <div style="padding: 0 0 177.7778% 0;"></div>
      <div
        id="g-annotation1-Artboard_69-img"
        class="g-aiImg"
        alt=""
        style="{`background-image: url(${chart916});`}"
      ></div>
      <div
        id="g-ai2-1"
        class="g-text g-aiAbs g-aiPointText"
        style="top:20.6335%;margin-top:-19.8px;left:4.2188%;width:253px;"
      >
        <p class="g-pstyle0">Wave forms from hitting reef, and</p>
        <p class="g-pstyle0">tube will track the line of the shelf</p>
      </div>
      <div
        id="g-ai2-2"
        class="g-text g-aiAbs g-aiPointText"
        style="top:24.448%;margin-top:-10.2px;left:78.0794%;width:170px;"
      >
        <p class="g-pstyle0">Solid southwest swell</p>
      </div>
      <div
        id="g-ai2-3"
        class="g-text g-aiAbs"
        style="top:50.8008%;left:25.6886%;width:48.5938%;"
      >
        <p>
          Tahitian local Vahine Fierro drops into a double overhead wave during
          a recent competition. Timing and position are critical to make the
          take-off and maximize scoring.
        </p>
      </div>
      <div
        id="g-ai2-4"
        class="g-text g-aiAbs g-aiPointText"
        style="top:94.5496%;margin-top:-19.8px;left:25.1109%;width:160px;"
      >
        <p class="g-pstyle0">Shallow water hides</p>
        <p class="g-pstyle0">a sharp reef</p>
      </div>
    </div>
  {/if}
</div>

<!-- End ai2html - 2024-07-18 12:39 -->

<style lang="scss">
  #g-annotation1-box,
  #g-annotation1-box .g-artboard {
    margin: 0 auto;
  }
  #g-annotation1-box p {
    margin: 0;
  }
  #g-annotation1-box .g-aiAbs {
    position: absolute;
  }
  #g-annotation1-box .g-aiImg {
    position: absolute;
    top: 0;
    display: block;
    width: 100% !important;
    height: 100%;
    background-size: contain;
    background-repeat: no-repeat;
  }
  #g-annotation1-box .g-aiPointText p {
    white-space: nowrap;
  }
  #g-annotation1-Artboard_67 {
    position: relative;
    overflow: hidden;
  }
  #g-annotation1-Artboard_67 p {
    font-family: 'Knowledge', 'Source Sans Pro', Arial, sans-serif;
    font-weight: 500;
    line-height: 19px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 16px;
    text-align: left;
    color: rgb(255, 255, 255);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-annotation1-Artboard_67 .g-pstyle0 {
    height: 19px;
  }
  #g-annotation1-Artboard_67 .g-pstyle1 {
    height: 19px;
    text-align: center;
  }
  #g-annotation1-Artboard_68 {
    position: relative;
    overflow: hidden;
  }
  #g-annotation1-Artboard_68 p {
    font-family: 'Knowledge', 'Source Sans Pro', Arial, sans-serif;
    font-weight: 500;
    line-height: 19px;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 16px;
    text-align: left;
    color: rgb(255, 255, 255);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    height: auto;
    position: static;
  }
  #g-annotation1-Artboard_68 .g-pstyle0 {
    height: 19px;
  }
  #g-annotation1-Artboard_68 .g-pstyle1 {
    height: 19px;
    text-align: center;
  }
  #g-annotation1-Artboard_69 {
    position: relative;
    overflow: hidden;
  }
  #g-annotation1-Artboard_69 p {
    font-family: 'Knowledge', 'Source Sans Pro', Arial, sans-serif;
    font-weight: 500;
    line-height: 19px;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 16px;
    text-align: left;
    color: rgb(255, 255, 255);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    height: auto;
    position: static;
  }
  #g-annotation1-Artboard_69 .g-pstyle0 {
    height: 19px;
  }

  /* Custom CSS */
  .text {
  }
</style>
