<!-- Generated by ai2html v0.100.0 - 2024-07-18 12:31 -->
<!-- ai file: annotation2.ai -->
<script>
  let width = null;
  // For demo purposes only, hard-wiring img paths from Vite
  // @ts-ignore
  import chart916 from '../imgs/anno_2_9_16.png';
  // @ts-ignore
  import chart11 from '../imgs/anno_2_1_1.png';
  // @ts-ignore
  import chart169 from '../imgs/anno_2_16_9.png';
  import { onMount } from 'svelte';
  export let onAiMounted = () => {};
  onMount(() => {
    onAiMounted();
  });
</script>

<div id="g-annotation2-box" bind:clientWidth="{width}">
  <!-- Artboard: Artboard_67 -->
  {#if width && width >= 1400}
    <div id="g-annotation2-Artboard_67" class="g-artboard" style="">
      <div style="padding: 0 0 56.25% 0;"></div>
      <div
        id="g-annotation2-Artboard_67-img"
        class="g-aiImg"
        alt=""
        style="{`background-image: url(${chart169});`}"
      ></div>
      <div
        id="g-ai0-1"
        class="g-text g-aiAbs g-aiPointText"
        style="top:23.4875%;margin-top:-39px;left:61.3242%;width:262px;"
      >
        <p class="g-pstyle0">The wave at Teahupo'o is known to</p>
        <p class="g-pstyle0">be very heavy with a thick lip that</p>
        <p class="g-pstyle0">can easily knock a surfer off the</p>
        <p class="g-pstyle0">wave and onto the reef below.</p>
      </div>
      <div
        id="g-ai0-2"
        class="g-text g-aiAbs"
        style="top:63.619%;left:40.8977%;width:14.1429%;"
      >
        <p>Surfer speed is up to</p>
        <p>35 km per hour (20 mph)</p>
      </div>
      <div
        id="g-ai0-3"
        class="g-text g-aiAbs"
        style="top:69.7143%;left:78.2443%;width:10.9286%;"
      >
        <p>1 cubic meter of water weighs 1 ton</p>
      </div>
      <div
        id="g-ai0-4"
        class="g-text g-aiAbs g-aiPointText"
        style="top:78.0145%;margin-top:-29.4px;left:20.6682%;width:275px;"
      >
        <p class="g-pstyle0">A surfer will adjust speed to stay in</p>
        <p class="g-pstyle0">the tube by dragging a hand to slow,</p>
        <p class="g-pstyle0">or pumping the board to speed up</p>
      </div>
    </div>
  {/if}
  <!-- Artboard: Artboard_68 -->
  {#if width && width >= 800 && width < 1400}
    <div id="g-annotation2-Artboard_68" class="g-artboard" style="">
      <div style="padding: 0 0 100% 0;"></div>
      <div
        id="g-annotation2-Artboard_68-img"
        class="g-aiImg"
        alt=""
        style="{`background-image: url(${chart11});`}"
      ></div>
      <div
        id="g-ai1-1"
        class="g-text g-aiAbs"
        style="top:19.75%;left:46.5424%;width:39.625%;"
      >
        <p>
          The wave at Teahupo'o is known to be very heavy with a thick lip that
          can easily knock a surfer off the wave and onto the reef below.
        </p>
      </div>
      <div
        id="g-ai1-2"
        class="g-text g-aiAbs"
        style="top:64%;left:27.6332%;width:21.25%;"
      >
        <p>Surfer speed is up to</p>
        <p>35 km per hour (20 mph)</p>
      </div>
      <div
        id="g-ai1-3"
        class="g-text g-aiAbs"
        style="top:64.5%;left:71.8695%;width:19.5%;"
      >
        <p>1 cubic meter of water weighs 1 ton</p>
      </div>
      <div
        id="g-ai1-4"
        class="g-text g-aiAbs"
        style="top:83.75%;left:12.3947%;width:31.25%;"
      >
        <p>
          A surfer will adjust speed to stay in the tube by dragging a hand to
          slow, or pumping the board to speed up
        </p>
      </div>
    </div>
  {/if}
  <!-- Artboard: Artboard_69 -->
  {#if width && width >= 0 && width < 800}
    <div id="g-annotation2-Artboard_69" class="g-artboard" style="">
      <div style="padding: 0 0 177.7778% 0;"></div>
      <div
        id="g-annotation2-Artboard_69-img"
        class="g-aiImg"
        alt=""
        style="{`background-image: url(${chart916});`}"
      ></div>
      <div
        id="g-ai2-1"
        class="g-text g-aiAbs g-aiPointText"
        style="top:21.8816%;margin-top:-39px;left:33.2378%;width:278px;"
      >
        <p class="g-pstyle0">The wave at Teahupo'o is known to</p>
        <p class="g-pstyle0">be very heavy with a thick lip that</p>
        <p class="g-pstyle0">can easily knock a surfer off the wave</p>
        <p class="g-pstyle0">and onto the reef below.</p>
      </div>
      <div
        id="g-ai2-2"
        class="g-text g-aiAbs"
        style="top:43.1543%;left:18.8458%;width:32.6563%;"
      >
        <p>Surfer speed is up to</p>
        <p>35 km per hour (20 mph)</p>
      </div>
      <div
        id="g-ai2-3"
        class="g-text g-aiAbs"
        style="top:81.2988%;left:63.0641%;width:30%;"
      >
        <p>1 cubic meter of water weighs 1 ton</p>
      </div>
      <div
        id="g-ai2-4"
        class="g-text g-aiAbs"
        style="top:89.4727%;left:5.0146%;width:48.125%;"
      >
        <p>
          A surfer will adjust speed to stay in the tube by dragging a hand to
          slow, or pumping the board to speed up
        </p>
      </div>
    </div>
  {/if}
</div>

<!-- End ai2html - 2024-07-18 12:31 -->

<style lang="scss">
  #g-annotation2-box,
  #g-annotation2-box .g-artboard {
    margin: 0 auto;
  }
  #g-annotation2-box p {
    margin: 0;
  }
  #g-annotation2-box .g-aiAbs {
    position: absolute;
  }
  #g-annotation2-box .g-aiImg {
    position: absolute;
    top: 0;
    display: block;
    width: 100% !important;
    height: 100%;
    background-size: contain;
    background-repeat: no-repeat;
  }
  #g-annotation2-box .g-aiPointText p {
    white-space: nowrap;
  }
  #g-annotation2-Artboard_67 {
    position: relative;
    overflow: hidden;
  }
  #g-annotation2-Artboard_67 p {
    font-family: 'Knowledge', 'Source Sans Pro', Arial, sans-serif;
    font-weight: 500;
    line-height: 19px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 16px;
    text-align: left;
    color: rgb(255, 255, 255);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-annotation2-Artboard_67 .g-pstyle0 {
    height: 19px;
  }
  #g-annotation2-Artboard_68 {
    position: relative;
    overflow: hidden;
  }
  #g-annotation2-Artboard_68 p {
    font-family: 'Knowledge', 'Source Sans Pro', Arial, sans-serif;
    font-weight: 500;
    line-height: 19px;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 16px;
    text-align: left;
    color: rgb(255, 255, 255);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    height: auto;
    position: static;
  }
  #g-annotation2-Artboard_69 {
    position: relative;
    overflow: hidden;
  }
  #g-annotation2-Artboard_69 p {
    font-family: 'Knowledge', 'Source Sans Pro', Arial, sans-serif;
    font-weight: 500;
    line-height: 19px;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 16px;
    text-align: left;
    color: rgb(255, 255, 255);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    height: auto;
    position: static;
  }
  #g-annotation2-Artboard_69 .g-pstyle0 {
    height: 19px;
  }

  /* Custom CSS */
  .text {
  }
</style>
