<!-- Generated by ai2html v0.100.0 - 2024-07-16 13:53 -->
<!-- ai file: sampleAnnotation.ai -->
<script>
  let width = null;
  // For demo purposes only, hard-wiring img paths from Vite
  // @ts-ignore
  import chart916 from '../imgs/anno_9_16.png';
  // @ts-ignore
  import chart11 from '../imgs/anno_1_1.png';
  // @ts-ignore
  import chart169 from '../imgs/anno_16_9.png';
  import { onMount } from 'svelte';
  export let onAiMounted = () => {};
  onMount(() => {
    onAiMounted();
  });
</script>

<div id="g-sampleAnnotation-box" bind:clientWidth="{width}">
  <!-- Artboard: Artboard_67 -->
  {#if width && width >= 1200}
    <div id="g-sampleAnnotation-Artboard_67" class="g-artboard" style="">
      <div style="padding: 0 0 56.25% 0;"></div>
      <div
        id="g-sampleAnnotation-Artboard_67-img"
        class="g-aiImg"
        alt=""
        style="{`background-image: url(${chart169});`}"
      ></div>
      <div
        id="g-ai0-1"
        class="g-text g-aiAbs g-aiPointText"
        style="top:49.9965%;margin-top:-10.5px;left:49.984%;margin-left:-91px;width:182px;"
      >
        <p class="g-pstyle0">Some annotation here...</p>
      </div>
    </div>
  {/if}
  <!-- Artboard: Artboard_70 -->
  {#if width && width >= 800 && width < 1200}
    <div id="g-sampleAnnotation-Artboard_70" class="g-artboard" style="">
      <div style="padding: 0 0 100% 0;"></div>
      <div
        id="g-sampleAnnotation-Artboard_70-img"
        class="g-aiImg"
        alt=""
        style="{`background-image: url(${chart11});`}"
      ></div>
      <div
        id="g-ai1-1"
        class="g-text g-aiAbs g-aiPointText"
        style="top:50.0595%;margin-top:-10.5px;left:49.9762%;margin-left:-91px;width:182px;"
      >
        <p class="g-pstyle0">Some annotation here...</p>
      </div>
    </div>
  {/if}
  <!-- Artboard: Artboard_71 -->
  {#if width && width >= 0 && width < 800}
    <div id="g-sampleAnnotation-Artboard_71" class="g-artboard" style="">
      <div style="padding: 0 0 177.7778% 0;"></div>
      <div
        id="g-sampleAnnotation-Artboard_71-img"
        class="g-aiImg"
        alt=""
        style="{`background-image: url(${chart916});`}"
      ></div>
      <div
        id="g-ai2-1"
        class="g-notes g-aiAbs g-aiPointText"
        style="top:50.0516%;margin-top:-10.5px;left:49.9217%;margin-left:-91px;width:182px;"
      >
        <p class="g-pstyle0">Some annotation here...</p>
      </div>
    </div>
  {/if}
</div>

<!-- End ai2html - 2024-07-16 13:53 -->

<style lang="scss">
  #g-sampleAnnotation-box,
  #g-sampleAnnotation-box .g-artboard {
    margin: 0 auto;
  }
  #g-sampleAnnotation-box p {
    margin: 0;
  }
  #g-sampleAnnotation-box .g-aiAbs {
    position: absolute;
  }
  #g-sampleAnnotation-box .g-aiImg {
    position: absolute;
    top: 0;
    display: block;
    width: 100% !important;
    height: 100%;
    background-size: contain;
    background-repeat: no-repeat;
  }
  #g-sampleAnnotation-box .g-aiPointText p {
    white-space: nowrap;
  }
  #g-sampleAnnotation-Artboard_67 {
    position: relative;
    overflow: hidden;
  }
  #g-sampleAnnotation-Artboard_67 p {
    font-family: 'Source Sans Pro', -apple-system, BlinkMacSystemFont,
      'Segoe UI', Roboto, 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-weight: 400;
    line-height: 19px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 16px;
    text-align: left;
    color: rgb(255, 255, 255);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-sampleAnnotation-Artboard_67 .g-pstyle0 {
    height: 19px;
    text-align: center;
  }
  #g-sampleAnnotation-Artboard_70 {
    position: relative;
    overflow: hidden;
  }
  #g-sampleAnnotation-Artboard_70 p {
    font-family: 'Source Sans Pro', -apple-system, BlinkMacSystemFont,
      'Segoe UI', Roboto, 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-weight: 400;
    line-height: 19px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 16px;
    text-align: left;
    color: rgb(255, 255, 255);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-sampleAnnotation-Artboard_70 .g-pstyle0 {
    height: 19px;
    text-align: center;
  }
  #g-sampleAnnotation-Artboard_71 {
    position: relative;
    overflow: hidden;
  }
  #g-sampleAnnotation-Artboard_71 p {
    font-family: 'Source Sans Pro', -apple-system, BlinkMacSystemFont,
      'Segoe UI', Roboto, 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-weight: 400;
    line-height: 19px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 16px;
    text-align: left;
    color: rgb(255, 255, 255);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-sampleAnnotation-Artboard_71 .g-pstyle0 {
    height: 19px;
    text-align: center;
  }

  /* Custom CSS */
  .text {
  }
</style>
