name: Notify downstream repositories

on:
  release:
    types: [published]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to bluprint_graphics-kit
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.REPO_PAT_TOKEN }}
          repository: reuters-graphics/bluprint_graphics-kit
          event-type: dependency-updated
